from __future__ import annotations

import json

from .planner import TestPlan


def _json(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def render_pytest(plan: TestPlan) -> str:
    lines = [
        '"""Generated by ConfigReach. Add assertions in your project tests; this file only supplies configuration cases."""',
        "",
        "import pytest",
        "",
        "CONFIGREACH_CASES = [",
    ]
    for case in plan.cases:
        mapping = ", ".join(f"{_json(k)}: {_json(v)}" for k, v in case.assignments)
        lines.append(f"    ({_json(case.case_id)}, {{{mapping}}}),")
    lines += [
        "]",
        "",
        "",
        "@pytest.fixture(params=CONFIGREACH_CASES, ids=lambda item: item[0])",
        "def configreach_env(request, monkeypatch):",
        "    case_id, values = request.param",
        "    for key, value in values.items():",
        "        monkeypatch.setenv(key, value)",
        "    return case_id, dict(values)",
        "",
    ]
    return "\n".join(lines)


def render_jest(plan: TestPlan) -> str:
    lines = [
        "// Generated by ConfigReach. This exports configuration cases only; add assertions in your tests.",
        "export const configReachCases = [",
    ]
    for case in plan.cases:
        config = ", ".join(f"{_json(k)}: {_json(v)}" for k, v in case.assignments)
        lines.append(f"  {{ id: {_json(case.case_id)}, configuration: {{{config}}} }},")
    lines += [
        "] as const;",
        "",
        "export function applyConfigReachCase(testCase: (typeof configReachCases)[number]) {",
        "  for (const [key, value] of Object.entries(testCase.configuration)) {",
        "    process.env[key] = value;",
        "  }",
        "  return testCase;",
        "}",
        "",
    ]
    return "\n".join(lines)


def render_go(plan: TestPlan) -> str:
    lines = [
        "// Code generated by ConfigReach. DO NOT EDIT by hand unless you intentionally take ownership.",
        "package configreachfixtures",
        "",
        "type Case struct {",
        "\tName string",
        "\tEnv  map[string]string",
        "}",
        "",
        "var Cases = []Case{",
    ]
    for case in plan.cases:
        lines.append(f"\t{{Name: {_json(case.case_id)}, Env: map[string]string{{")
        for key, value in case.assignments:
            lines.append(f"\t\t{_json(key)}: {_json(value)},")
        lines.append("\t}},")
    lines += ["}", ""]
    return "\n".join(lines)


def render_shell(plan: TestPlan) -> str:
    lines = [
        "#!/usr/bin/env sh",
        "# Generated by ConfigReach. Source or adapt one case at a time in your test harness.",
        "",
    ]
    for case in plan.cases:
        lines.append(f"# {case.case_id} [{case.scope}]")
        for key, value in case.assignments:
            escaped = value.replace("'", "'\"'\"'")
            lines.append(f"export {key}='{escaped}'")
        lines.append("")
    return "\n".join(lines)


def render_junit(plan: TestPlan) -> str:
    lines = [
        "// Generated by ConfigReach. Supplies configuration cases only; add assertions in your JUnit tests.",
        "import java.util.Map;",
        "import java.util.stream.Stream;",
        "import org.junit.jupiter.params.provider.Arguments;",
        "",
        "public final class ConfigReachCases {",
        "    private ConfigReachCases() {}",
        "",
        "    public static Stream<Arguments> cases() {",
    ]
    if not plan.cases:
        lines.append("        return Stream.empty();")
    else:
        lines.append("        return Stream.of(")
        for index, case in enumerate(plan.cases):
            entries = ", ".join(
                f"Map.entry({_json(key)}, {_json(value)})" for key, value in case.assignments
            )
            comma = "," if index < len(plan.cases) - 1 else ""
            lines.append(
                f"            Arguments.of({_json(case.case_id)}, Map.ofEntries({entries})){comma}"
            )
        lines.append("        );")
    lines += ["    }", "}", ""]
    return "\n".join(lines)


def render_xunit(plan: TestPlan) -> str:
    lines = [
        "// Generated by ConfigReach. Supplies configuration cases only; add assertions in your xUnit tests.",
        "using System;",
        "using System.Collections.Generic;",
        "",
        "public static class ConfigReachCases",
        "{",
        "    public static IEnumerable<object[]> Cases",
        "    {",
        "        get",
        "        {",
    ]
    for case in plan.cases:
        lines.append("            yield return new object[]")
        lines.append("            {")
        lines.append(f"                {_json(case.case_id)},")
        lines.append("                new Dictionary<string, string>")
        lines.append("                {")
        for key, value in case.assignments:
            lines.append(f"                    [{_json(key)}] = {_json(value)},")
        lines += ["                }", "            };" ]
    lines += [
        "        }",
        "    }",
        "",
        "    public static void Apply(IReadOnlyDictionary<string, string> values)",
        "    {",
        "        foreach (var pair in values)",
        "        {",
        "            Environment.SetEnvironmentVariable(pair.Key, pair.Value);",
        "        }",
        "    }",
        "}",
        "",
    ]
    return "\n".join(lines)


FIXTURE_FORMATS = {
    "pytest": render_pytest,
    "jest": render_jest,
    "go": render_go,
    "shell": render_shell,
    "junit": render_junit,
    "xunit": render_xunit,
}


def render_fixture(plan: TestPlan, framework: str) -> str:
    try:
        renderer = FIXTURE_FORMATS[framework]
    except KeyError as exc:
        raise ValueError(f"unsupported fixture framework: {framework}") from exc
    return renderer(plan)
